version: '3'
services:
  ongdb:
    image:  graphfoundation/ongdb:3.6
    container_name: ongdb-test
    # environment:
      # - NEO4J_AUTH=neo4j/test
      # NEO4J_AUTH: 'neo4j/test'
    volumes:
      - ./ongdb/data:/data
    ports:
      - 7474:7474
      - 7687:7687