version: '3'
services:
  cassandra:
    image: bitnami/cassandra:latest
    container_name: cassandra
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: 
    #   POSTGRES_DB: customer
    #   POSTGRES_HOST_AUTH_METHOD: trust
    # env_file:
    #   - database.env # configure postgres
    
    volumes:
      - ./out/cassandra_data:/var/lib/cassandra
    ports: 
      - 9042:9042 #cqlsh
      - 7199:7199 #jmx
      - 7000:7000 #internode communication
      - 7001:7001 #tls internode
      - 9160:9160 #client api
